In [1]:
import numpy as np
#first step
simple_array=np.array([[1,2,3],[2,4,5]])
print (simple_array)
print(simple_array.shape)
print(simple_array.size)
print(simple_array.reshape(3,2))
print(simple_array[1,2])

#second step,custom tables,random
second_array=np.array([1,2,3],dtype=int)
print(second_array)

a = np.zeros((3,3))
print(a)
b = np.ones((4,5))
print(b)
c = np.full((5,5),5)
print(c)
d =np.random.random((3,3))
print(d)

#step for knowing a bit about int function,
#int16,int32,int64 and uint for avoiding minus
func_int=np.array([433,454,65665],dtype=np.int16)
print(func_int)
minus_int=np.array([-3434,343,545],dtype=np.uint16)
print(minus_int)

#step four
a = [23,34,45,32,56]
b =[32,45,7,8,5]
c = [1,23,4,5,2]
d = [12,334,555,34,5]
att_arrays = np.array([a,b,c,d])
print(att_arrays)
print ( 'culomn' ,att_arrays[:,0:3:1])
print ( 'row' ,att_arrays[0:3:1])

att_cond = att_arrays > 20
print(att_cond)
print(att_arrays[att_cond])
where_cond = np.where(att_arrays > 20,att_arrays,'error')
print(where_cond)
logical_and = np.logical_and(att_arrays>20,att_arrays<100)
print(logical_and)
print(att_arrays[logical_and])
where_cond2 = np.where(logical_and,att_arrays,0)
print(where_cond2)

#step five 
arenge_array = np.arange(0,100,2)
print(arenge_array)
print(arenge_array.reshape(5,10))
print(np.where(arenge_array>20,arenge_array+2,-1))

#step six,simple math
a = np.array([[23,34,45,32,56],[32,45,7,8,5]],dtype=np.int64)
b =np.array([32,45,7,8,5])
c = np.array([1,23,4,5,2])
d = np.array([12,334,555,34,5])
print(a.sum(axis=1))
print(a.cumsum())
print(a.prod())
print(a.cumprod())
print(a+b)
print(np.dot(a,b))
#some extra maht,if you want to run broadcost,you have to be sure that the culomns or the rows are aquel
a = np.array([[23,34,45,32,56],[32,45,7,8,5]],dtype=np.int64)
b =np.array([32,45,7,8,5])
print(a.min())
print(a.max())
print(a.mean())
print(a.ptp())
print(b.ptp())
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.ptp())
#THIS IS THE END OF BESIC NUMPY

[[1 2 3]
 [2 4 5]]
(2, 3)
6
[[1 2]
 [3 2]
 [4 5]]
5
[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0.38583132 0.43634596 0.0009982 ]
 [0.05549153 0.93006634 0.09063408]
 [0.30212147 0.84174094 0.08138533]]
[433 454 129]
[62102   343   545]
[[ 23  34  45  32  56]
 [ 32  45   7   8   5]
 [  1  23   4   5   2]
 [ 12 334 555  34   5]]
culomn [[ 23  34  45]
 [ 32  45   7]
 [  1  23   4]
 [ 12 334 555]]
row [[23 34 45 32 56]
 [32 45  7  8  5]
 [ 1 23  4  5  2]]
[[ True  True  True  True  True]
 [ True  True False False False]
 [False  True False False False]
 [False  True  True  True False]]
[ 23  34  45  32  56  32  45  23 334 555  34]
[['23' '34' '45' '32' '56']
 ['32' '45' 'error' 'error' 'error']
 ['error' '23' 'error' 'error' 'error']
 ['error' '334' '555' '34' 'error']]
[[ True  True  True  True  True]
 [ True  True False False False]
 [False  True 