In [2]:
import numpy as np

In [38]:
array = np.array([[1,2,3,4],[6,7,8,9]])
array.dtype
array.size
array.reshape(4,2)
array[1,1]

7

In [22]:
array_2 = np.array({'rifat':13,'arafat':15})
array_2.size

1

In [88]:
a = [23,34,45,32,56]
b =[32,45,7,8,5]
c = [1,23,4,5,2]
d = [12,334,555,34,5]
array = np.array([a,b,c,d])
array

array([[ 23,  34,  45,  32,  56],
       [ 32,  45,   7,   8,   5],
       [  1,  23,   4,   5,   2],
       [ 12, 334, 555,  34,   5]])

In [61]:
nr = np.random.randint(1,10,5)
nr

array([2, 3, 7, 5, 6])

In [79]:
print(ar[:,0:2])

[[ 23  34]
 [ 32  45]
 [  1  23]
 [ 12 334]]


In [94]:
i = array>5
array[i]

array([ 23,  34,  45,  32,  56,  32,  45,   7,   8,  23,  12, 334, 555,
        34])

In [111]:
np.where(array > 5,array,None) #sob gulai asbe condition er baki gula icca moto show korbe

array([[23, 34, 45, 32, 56],
       [32, 45, 7, 8, None],
       [None, 23, None, None, None],
       [12, 334, 555, 34, None]], dtype=object)

In [113]:
r = np.logical_and(array>5,array<20)
array[r]

array([ 7,  8, 12])

In [131]:
a = np.array([23,34,45,32,56])
b =np.array([32,45,7,8,5])
sum_array = np.array([a,b],dtype = np.int64)
np.cumprod(sum_array)
print(a+b)
np.dot(a,b)
np.ptp(b) #max - min
np.mean(a)

[55 79 52 40 61]


38.0

## using numpy;
# dimantional array using np.array
# random number as I wish to,using np.random.no import
# some logical operation using > ,where,and logical_end
# besic math operation and more other
